import React, { useEffect } from "react";
import { StateContextProvider } from "../../context/stateContext";
import './globals.css'
export const metadata = {
  title: "My Awesome Site",
  description: "Generated by Next + Sanity",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="mx-[3rem]">
        <StateContextProvider>
          <div >{children}</div>
        </StateContextProvider>
      </body>
    </html>
  );
}
